Provision application codes

diff --git a/.github/workflows/4.doctl-app-platform.yml b/.github/workflows/4.doctl-app-platform.yml
--- a/.github/workflows/4.doctl-app-platform.yml
+++ b/.github/workflows/4.doctl-app-platform.yml
@@ -43,6 +43,16 @@ jobs:
         run: |
           echo environment: ${{ inputs.environment || 'N/A' }}
 
+      - name: Get project details
+        run: |
+          PROJECT_ID=$(doctl projects list --format ID,Name --no-header | awk -v name=TAMS '$2 == name {print $1}')
+          if [[ -z "$PROJECT_ID" ]]; then
+            echo "❌ Error: Project 'TAMS' not found!"
+            exit 1
+          fi
+          echo "✅ Found Project ID: $PROJECT_ID"
+          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
+
       - name: Check if App Platform is Exists
         run: |
           APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep tams-web-application | awk '{print $1}')
@@ -61,7 +71,7 @@ jobs:
         run: |
           set -euo pipefail
           echo "App does not exist. Creating new app..."
-          doctl apps create --spec .github/workflows/tams-app-spec.json --format ID,DefaultIngress,Created --wait --project-id TAMS
+          doctl apps create --spec .github/workflows/tams-app-spec.json --format ID,DefaultIngress,Created --wait --project-id "$PROJECT_ID"
           
           #Get App Platform ID for this application.
           APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep tams-web-application | awk '{print $1}')
